### ISSUE TITLE
Нехватка памяти при загрузке изображения

### ISSUE THREAD

**Issue by yankovskiy** [yankovskiy/PhotohuntAndroid#8]
device: HTC One SV (k2ul) 
OS: Android 4.2
app: 0.4-beta+

java.lang.OutOfMemoryError: (Heap Size=65536KB, Allocated=60033KB)
at android.graphics.Bitmap.nativeCreateScaledBitmap(Native Method)
at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:809)
at ru.neverdark.photohunt.utils.Common.resizeBitmap(Common.java:34)
at ru.neverdark.photohunt.fragments.UploadImageFragment.loadImage(UploadImageFragment.java:123)
at ru.neverdark.photohunt.fragments.UploadImageFragment.onCreateView(UploadImageFragment.java:117)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1231)
at android.app.Activity.performStart(Activity.java:5175)
at android.app.Activity.performRestart(Activity.java:5230)
at android.app.Activity.performResume(Activity.java:5249)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3183)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3238)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1408)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:5751)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
at dalvik.system.NativeStart.main(Native Method)

**Comment by yankovskiy** [comment]
fixed
